lane :automated_feature_bugfix do
  puts 'we are in the feature_bugfix LANE'
end

lane :automated_dev_release do
  puts 'we are in the dev_release lane'
end

lane :publish_dev_release do
  puts 'we are in the publish_dev_release lane'
end
