# This is a basic workflow to help you get started with Actions

name: fl-ios-app

# Controls when the workflow will run
on:
  push:
    branches:
      - "testing**" ##these names should make sense with RMS branch naming. Ask Cassidy if FLMP and FLAP should be distiguished
      - 'bugfix*' 
      #- 'testing*' ##have to add the slashed in order for /FLMP to work. can't be testing*
      - 'main'  ##main gets skipped because it is not referenced in line 17. 
      #- 'testing/**' 

jobs: 
    BugFixes: 
      name: bugFix
      if: startsWith(github.ref, 'refs/heads/testing') ##or whatever the branch name for bug fix is. 
      uses:  ./.github/workflows/reusable_workflow.yml #@using Steph's version. but maybe change to @foghorn-dev.orV# 
      with: 
          lane: drive_automated_feature_bugfix ###have to fix up lane names. better lane names that describes whats going on. 
  
    # feature-dev:
    #   - name: devv-release
    #           if: github.ref == 'refs/heads/dev-release' ##or whatever the branch name is. 
    #           uses:  ./.github/workflows/reusable_workflow.yml
    #           with: 
    #             lane: drive_automated_dev_release
    #             # ${{github.event.inputs.print_lane}}
 
    # publish_dev_release:
    #         - name: publishh
    #           if: github.ref == 'refs/heads/pub-dev-release' ##or whatever the branch name is. 
    #           uses:  ./.github/workflows/reusable_workflow.yml
    #           with: 
    #             lane: drive_publish_dev_release
    #             # ${{github.event.inputs.print_lane}}
