# This is a basic workflow to help you get started with Actions

name: fl-ios-app

# Controls when the workflow will run
on:
  push:
    branches:
      - "feature**" ##these names should make sense with RMS branch naming. Ask Cassidy if FLMP and FLAP should be distiguished
      - 'bugfix**'  
      - 'dev' # with 'dev*'?
      - 'release**'


jobs: 
    BugFixes_branch: 
      name: bugFix
      if: startsWith(github.ref, 'refs/heads/bugfix')
      uses:  ./.github/workflows/reusable_workflow.yml #@using Steph's version. 
      with: 
          lane: feature_bugfix
  
    Feature_branch:
      name: feature 
      if: startsWith(github.ref, 'refs/heads/feature')
      uses:  ./.github/workflows/reusable_workflow.yml
      with:
          lane: feature_bugfix
 
    Dev_branch:
      steps:
        - name: dev_lane
          if: github.ref == 'refs/heads/dev' ##or whatever the branch name is. 
          uses:  ./.github/workflows/reusable_workflow.yml
          with:
            lane: dev_release 
        - name: publish_dev_release
          if: github.ref == 'refs/heads/dev' ##or whatever the branch name is. 
          uses:  ./.github/workflows/reusable_workflow.yml
          with:
            lane: publish_dev_release

    # Dev_publish:
    #   name: publish_dev_release
    #   if: github.ref == 'refs/heads/dev' ##or whatever the branch name is. 
    #   uses:  ./.github/workflows/reusable_workflow.yml
    #   with:
    #     lane: publish_dev_release
    






    # publish_dev_release:
    #         - name: publishh
    #           if: github.ref == 'refs/heads/pub-dev-release' ##or whatever the branch name is. 
    #           uses:  ./.github/workflows/reusable_workflow.yml
    #           with: 
    #             lane: drive_publish_dev_release
    #             # ${{github.event.inputs.print_lane}}
