# This is a basic workflow to help you get started with Actions

name: fl-ios-app

# Controls when the workflow will run
on:
  push:
    branches:
      - "*"
    # workflow_dispatch:
    #     inputs:
    #         print_lane: 
    #              type: string 
    #              required: true
    #              description: print out the lane NAME.   

jobs: 
    name-job:
      name: bugFix
      if: startsWith(github.ref, 'refs/heads/testing') #github.ref == 'refs/heads/main' ##or whatever the branch name for bug fix is. 
      uses:  ./.github/workflows/reusable_workflow.yml #@using Steph's version. but maybe change to @foghorn-dev.orV# 
      with: 
          print_me: drive_automated_feature_bugfix 
          #run: echo ${{github.event.inputs.print_lane}}
                # ${{github.event.inputs.print_lane}}

    # feature-dev-release:
    #   - name: devv-release
    #           if: github.ref == 'refs/heads/dev-release' ##or whatever the branch name is. 
    #           uses:  ./.github/workflows/reusable_workflow.yml
    #           with: 
    #             lane: drive_automated_dev_release
    #             # ${{github.event.inputs.print_lane}}
 
    # publish_dev_release:
    #         - name: publishh
    #           if: github.ref == 'refs/heads/pub-dev-release' ##or whatever the branch name is. 
    #           uses:  ./.github/workflows/reusable_workflow.yml
    #           with: 
    #             lane: drive_publish_dev_release
    #             # ${{github.event.inputs.print_lane}}
