# This is a basic workflow to help you get started with Actions

name: fl-ios-app

# Controls when the workflow will run
on:
  push:
    branches:
      - "feature**" ##these names should make sense with RMS branch naming. Ask Cassidy if FLMP and FLAP should be distiguished
      - 'bugfix**'  
      - 'dev*' # with 'dev*'?
      - 'release**'


jobs: 
    BugFixes_branch: 
      name: bugFix
      if: startsWith(github.ref, 'refs/heads/bugfix')
      uses:  ./.github/workflows/reusable_workflow.yml #@using Steph's version. 
      with: 
          lane: feature_bugfix
  
    Feature_branch:
      name: feature 
      if: startsWith(github.ref, 'refs/heads/feature')
      uses:  ./.github/workflows/reusable_workflow.yml
      with:
          lane: feature_bugfix
 
    # Dev_branch:
    #   name: dev
    #   if: startsWith(github.ref, 'refs/heads/dev') ##or whatever the branch name is. 
    #   uses:  ./.github/workflows/reusable_workflow.yml
    #   with:
    #     lane: dev_release 
    #     # - name: publish_dev_release
    #     #   if: github.ref == 'refs/heads/dev' ##or whatever the branch name is. 
    #     #   uses:  ./.github/workflows/reusable_workflow.yml
    #     #   with:
    #     #     lane: publish_dev_release

    Dev_branch:
      name: Dev release and publish
      runs-on: macos-latest
      steps:
        - name: dev
          if: startsWith(github.ref, 'refs/heads/dev') ##or whatever the branch name is. 
          uses:  ./.github/workflows/reusable_workflow.yml
          with:
            lane: dev_release 
        - name: publish_dev_release
          if: github.ref == 'refs/heads/dev' ##or whatever the branch name is. 
          uses:  ./.github/workflows/reusable_workflow.yml
          with:
            lane: publish_dev_release

    # Publish_Dev:
    #   name: publish_dev
    #   if: startsWith(github.ref, 'refs/heads/dev') ##or whatever the branch name is. 
    #   uses:  ./.github/workflows/reusable_workflow.yml
    #   with:
    #     lane: publish_dev_release
    
    Release_branch:
      name: release
      if: startsWith(github.ref, 'refs/heads/release') ##or whatever the branch name is. 
      uses:  ./.github/workflows/reusable_workflow.yml
      with:
        lane: dev_release 

    Publish_Release:
      name: publish_release
      if: startsWith(github.ref, 'refs/heads/release') ##or whatever the branch name is. 
      uses:  ./.github/workflows/reusable_workflow.yml
      with:
        lane: publish_dev_release

