# This is a basic workflow to help you get started with Actions

name: fl-ios-app

# Controls when the workflow will run
on:
  push:
    branches:
      - "testing*" ##these names should make sense with RMS branch naming. 
      - 'bugfix*'
      - 'testing/FLMP*'
      - 'main'  

jobs: 
    BugFixes: 
      name: bugFix
      if: startsWith(github.ref, 'refs/heads/testing') ##or whatever the branch name for bug fix is. 
      uses:  ./.github/workflows/reusable_workflow.yml #@using Steph's version. but maybe change to @foghorn-dev.orV# 
      with: 
          lane: drive_automated_feature_bugfix 
  
    # feature-dev:
    #   - name: devv-release
    #           if: github.ref == 'refs/heads/dev-release' ##or whatever the branch name is. 
    #           uses:  ./.github/workflows/reusable_workflow.yml
    #           with: 
    #             lane: drive_automated_dev_release
    #             # ${{github.event.inputs.print_lane}}
 
    # publish_dev_release:
    #         - name: publishh
    #           if: github.ref == 'refs/heads/pub-dev-release' ##or whatever the branch name is. 
    #           uses:  ./.github/workflows/reusable_workflow.yml
    #           with: 
    #             lane: drive_publish_dev_release
    #             # ${{github.event.inputs.print_lane}}
