name: Manual Release workflow dispatch.

on: 
  workflow_dispatch:
    # inputs: 
    #   lanes: 
    #     type: string
    #     required: true
    #     description: What is the lane name?
      # env:
      #   type: string 
      #   required: true
      #   description: What is the env variable?

jobs: 
    Publish_Release:
      name: publish_release
      if: startsWith(github.ref, 'refs/heads/release') ##or whatever the branch name is. 
      uses:  ./.github/workflows/reusable_workflow.yml
      with:
        lane: publish_dev_release
        env: another env input