name: reusable FILE

on: 
  workflow_call:
    inputs:
      print_me:
        type: string 
        required: true
        description: String prints out from reusable_workflow.
        
        
jobs:
  print_input:
    runs-on: ubuntu-latest
    steps:
      - name: printing the input
        run: |
          echo "${{ inputs.print_me }}" 
