name: Android workflow-dispatch WF_D

on: 
  workflow_dispatch:
    inputs: 
      regionFlag: 
        type: string
        required: true
        description: US or EU?

jobs:
  Here:
    runs-on: ubuntu-latest
    steps:
      - name: Random_output
        run: echo SOMETHING RANDOM ON LINE 16
      - name: Bashie file
        uses: ./bash.sh
        with: 
          regionFlag: ${{ github.event.inputs.regionFlag }}
          run: echo ${{ github.event.inputs.regionFlag }}