name: Manually tirggered workflow.

on: 
  push:
    branches:
      #- 'dev'
      - 'release**'
  workflow_dispatch:
    inputs: 
      env:
        type: string 
        required: true
        description: What is the env variable?

jobs: 
    Publish_Dev:
      name: publish_dev
      if: startsWith(github.ref, 'refs/heads/dev') ##or whatever the branch name is. 
      uses:  ./.github/workflows/reusable_workflow.yml
      with:
        #lane: publish_dev_release
        env: some env input 
    
    Publish_Release:
      name: publish_release
      if: startsWith(github.ref, 'refs/heads/release') ##or whatever the branch name is. 
      uses:  ./.github/workflows/reusable_workflow.yml
      with:
        #lane: publish_dev_release
        env: another env input 